//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbmg.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dbmg.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE foo (
        ///    id integer primary key,
        ///    name varchar(50)
        ///);
        ///
        ///GO
        ///
        ///INSERT INTO foo (id, name) VALUES (1, &apos;Chris Davies&apos;);.
        /// </summary>
        internal static string Sql000 {
            get {
                return ResourceManager.GetString("Sql000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO foo (id, name) VALUES (2, &apos;G.K. Chesterton&apos;);
        ///INSERT INTO foo (id, name) VALUES (3, &apos;C.S. Lewis&apos;);
        ///INSERT INTO foo (id, name) VALUES (4, &apos;J.R.R. Tolkien&apos;);
        ///INSERT INTO foo (id, name) VALUES (5, &apos;Thomas Merton&apos;);.
        /// </summary>
        internal static string Sql001 {
            get {
                return ResourceManager.GetString("Sql001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO foo (id, name) VALUES (6, &apos;Hello World&apos;);.
        /// </summary>
        internal static string Sql002 {
            get {
                return ResourceManager.GetString("Sql002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO foo (id, name) VALUES (7, &apos;Cookie Monster&apos;);.
        /// </summary>
        internal static string Sql003 {
            get {
                return ResourceManager.GetString("Sql003", resourceCulture);
            }
        }
    }
}
